### ISSUE TITLE
Weird behaviour while jumping among punctations.

### ISSUE THREAD

**Issue by cireu** [cireu/jieba.el#6]
https://emacs-china.org/t/jieba-el-emacs-jieba/9384/35?u=cireu

**Comment by chen-chao** [comment]
额, 原来 fix 还会显示在 issue 里面...

我移除了 thing-at-point 相关的代码, 可以的话我开个 PR.

**Comment by cireu** [comment]
行 @chen-chao 不过现在我没时间修jieba，在搞TiKV的一些PR

**Comment by chen-chao** [comment]
没事, 等你有空再说.
